only: pulls

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
- meta/staleproof
# Label to use when marking an issue as stale
staleLabel: meta/stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This pull request has been automatically flagged for inactivity because it has not
  been acted upon in the last 60 days. It will be closed if no new activity
  occurs in the next 30 days. Please comment on this pull request
  if you feel this has happened by mistake. Thank you for your contributions!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Closing due to inactivity. If you feel this was a mistake or you wish to
  re-open at any time in the future, please leave a comment and it will be
  re-surfaced for the maintainers to review.
